project:
  name: imdb-sentiment-analysis
  author: Ghulam
  version: 1.0

data:
  raw_path: "data/raw/IMDB Dataset.csv"
  processed_dir: "data/processed/"
  train_file: "train.csv"
  val_file: "val.csv"
  test_file: "test.csv"
  test_size: 0.15
  val_size: 0.15
  random_state: 42

baseline_model:
  vectorizer:
    max_features: 10000
    ngram_range: [1, 2]
  classifier:
    type: "logistic_regression"
    C: 1.0
    max_iter: 1000

transformer_model:
  model_name: "distilbert-base-uncased"
  max_length: 256
  batch_size: 16
  epochs: 2
  learning_rate: 5e-5

deployment:
  api_host: "0.0.0.0"
  api_port: 8000
